var Student = module.exports = {
  all: function(){
    return [
      {github: "APARK87", name:"Aaron Park"},
      {github: "amaseda", name:"Adrian Maseda"},
      {github: "AliTopal8", name:"Ali Topaloglu"},
      {github: "britbrith4", name:"Brittany Henson"},
      {github: "chadxsmith", name:"Chad Smith"},
      {github: "Freetown5", name:"Isa Conteh"},
      {github: "theeltahir", name:"Eltahir Eltahir"},
      {github: "seekpeace", name:"Enoch Shin"},
      {github: "Tuzibun", name:"Gwen Mak"},
      {github: "hharper", name:"Haleigh Harper"},
      {github: "janicemin", name:"Janice Min"},
      {github: "JYamauchi", name:"Jared Yamauchi"},
      {github: "juliar0se", name:"Julia Rose"},
      {github: "keithknox", name:"Keith Knox"},
      {github: "lmdragun", name:"Lindsey Dragun"},
      {github: "KMG112", name:"Matt Wuertz"},
      {github: "michaelkendall", name:"Michael Kendall"},
      {github: "nhashmi", name:"Nabil Hashmi"},
      {github: "nbumbarger", name:"Nick Bumbarger"},
      {github: "pmander90", name:"Parmeet Singh"},
      {github: "presto2116", name:"Preston Straight"},
      {github: "ryankeiper", name:"Ryan Keiper"},
      {github: "greenes", name:"Sarah Greene"},
      {github: "mugshepherd", name:"Toby Schaeffer"},
      {github: "nclevine", name:"Noah Levine"},
      {github: "opbiboy", name:"Biboy Pratama"},
      {github: "htylerbrooks", name:"Tyler Brooks"},
      {github: "tsetoung", name:"John Moua"},
      {github: "uhhlittle", name:"Allison Little"},
      {github: "hellostella", name:"Kevin Bauer"},
      {github: "philw214", name:"Phillip Winston"},
      {github: "btf5048", name:"Brad Foster"},
      {github: "luminousbeam", name:"Jocelyn Jeriah"},
      {github: "tpeters0", name:"Tamara Peters"},
      {github: "joehurowitz", name:"Joe Hurowitz"},
      {github: "Vaalys", name:"Ammie McCullough"},
      {github: "ZakkMan", name:"Zakk Man"},
      {github: "SmallNic", name:"Nic Small"},
      {github: "dmjurg", name:"Diana Jurglelewicz"},
      {github: "dmc2015", name:"Don McLamb"},
      {github: "DamonMd", name:"Damon Emde"},
      {github: "ifthesim", name:"Alif Chowdhury"},
      {github: "Karen-O", name:"Karen Ochsenreiter"},
      {github: "RodJA32", name:"Rodger Anderson"}
    ]
  }
}